// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * Error value that crosses process boundaries (Tauri IPC, D-Bus, MCP).
 *
 * `message` is a technical English description for logs and AI hosts. The UI
 * never shows it as the primary text; it renders a localized text for `code`
 * and offers `message` as detail.
 */
export type AppError = { code: ErrorCode, message: string, 
/**
 * Optional technical detail (e.g. sanitized pacman error line).
 */
detail: string | null, };
