// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendStatus } from "./BackendStatus";

/**
 * General information about the running application.
 */
export type AppInfo = { version: string, appId: string, 
/**
 * Preferred UI language derived from `LANG`/`LC_MESSAGES` (`de` or `en`).
 */
systemLanguage: string, 
/**
 * Desktop color scheme preference (`dark`, `light` or `unknown`).
 */
systemColorScheme: string, 
/**
 * The privileged helper is installed and reachable on the system bus.
 */
helperAvailable: boolean, 
/**
 * Reason when the helper is not reachable.
 */
helperError: string | null, backend: BackendStatus, 
/**
 * Development build using the session-bus test helper.
 */
developmentMode: boolean, };
