// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoUpdatePolicy } from "./AutoUpdatePolicy";
import type { UpdateWindow } from "./UpdateWindow";

/**
 * Content of `/etc/cachyos-center/auto-update.toml`.
 */
export type AutoUpdateConfig = { policy: AutoUpdatePolicy, window: UpdateWindow, 
/**
 * Require a successful snapper snapshot before preparing an update.
 */
requireSnapshot: boolean, 
/**
 * News published up to this time have been read and acknowledged in the UI.
 */
newsAcknowledgedUntil: number | null, };
