// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoUpdateConfig } from "./AutoUpdateConfig";
import type { ExternalUpdater } from "./ExternalUpdater";
import type { OfflineUpdateStatus } from "./OfflineUpdateStatus";
import type { Operation } from "./Operation";

/**
 * Everything the settings page needs to show about automatic updates.
 */
export type AutoUpdateStatus = { config: AutoUpdateConfig, 
/**
 * The policy file could not be read (defaults are shown).
 */
configError: string | null, 
/**
 * The app timer `cachyos-center-preflight.timer` is enabled.
 */
timerEnabled: boolean, nextRun: number | null, lastRun: number | null, 
/**
 * Result of the last timer run (written by the helper).
 */
lastResult: Operation | null, 
/**
 * The update is prepared and will be installed on the next reboot.
 */
preparedForNextReboot: boolean, offline: OfflineUpdateStatus, externalUpdaters: Array<ExternalUpdater>, 
/**
 * `PrepareForNextReboot` is still in development and must be unlocked by the
 * administrator (`/etc/cachyos-center/experimental.toml`).
 */
prepareModeAvailable: boolean, 
/**
 * Reasons why `PrepareForNextReboot` cannot be activated right now.
 */
prepareModeBlockers: Array<string>, 
/**
 * The privileged helper is installed and reachable.
 */
helperAvailable: boolean, };
