// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Availability of the libalpm bridge.
 */
export type BackendStatus = { "state": "ready", libalpmVersion: string, builtAgainst: string, } | { "state": "unavailable", reason: string, };
