// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the package backend (libalpm bridge) is unavailable.
 */
export type BackendProblem = "incompatible" | "bridgeMissing" | "failed";
