// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendProblem } from "./BackendProblem";

/**
 * Availability of the libalpm bridge.
 */
export type BackendStatus = { "state": "ready", libalpmVersion: string, builtAgainst: string, } | { "state": "unavailable", problem: BackendProblem, reason: string, };
