// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Installation status filter for the repository catalog.
 */
export type CatalogInstallFilter = "any" | "installed" | "notInstalled";
