// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogInstallFilter } from "./CatalogInstallFilter";

/**
 * Query for the repository catalog (configured pacman repositories only).
 */
export type CatalogQuery = { query: string, repository: string | null, installFilter: CatalogInstallFilter, limit: number, };
