// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Package changes of an operation, counted from the pacman log (authoritative).
 */
export type ChangeCounts = { installed: number, upgraded: number, downgraded: number, reinstalled: number, removed: number, 
/**
 * Affected package names (at most 20).
 */
packages: Array<string>, };
