// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the most recent update check.
 */
export type CheckStatus = "neverChecked" | "fresh" | "stale" | "failed" | "prerequisiteMissing" | "unsupported";
