// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `.pacnew`/`.pacsave` file below `/etc`.
 */
export type ConfigFileHint = { 
/**
 * Absolute path below `/etc`.
 */
path: string, 
/**
 * `pacnew` or `pacsave`.
 */
kind: string, modifiedAt: number | null, };
