// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CpuInfo = { model: string, vendor: string | null, cores: number, threads: number, 
/**
 * Highest supported x86-64 micro-architecture level (e.g. `x86-64-v3`).
 */
isaLevel: string | null, };
