// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthItem } from "./HealthItem";
import type { HistoryEntry } from "./HistoryEntry";
import type { LockStatus } from "./LockStatus";
import type { Severity } from "./Severity";
import type { SystemSummary } from "./SystemSummary";
import type { UpdateCheckResult } from "./UpdateCheckResult";

/**
 * Data of the dashboard ("Übersicht").
 */
export type Dashboard = { system: SystemSummary, updates: UpdateCheckResult, lock: LockStatus, installedCount: number, foreignCount: number, healthItems: Array<HealthItem>, healthWorst: Severity | null, lastActivity: HistoryEntry | null, 
/**
 * Last completed full system upgrade (pacman log).
 */
lastFullUpgrade: number | null, 
/**
 * Next background check of the running app (settings interval).
 */
nextCheckAt: number | null, 
/**
 * An update is prepared by pacman-offline for the next reboot.
 */
offlineUpdatePrepared: boolean, rebootRecommended: boolean, collectedAt: number, };
