// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskInfo = { 
/**
 * Mount point (`/`, `/var/cache/pacman/pkg`, ...). Never a home directory.
 */
mountPoint: string, filesystem: string, totalBytes: number, availableBytes: number, };
