// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable, machine readable error code.
 *
 * The UI maps each code to a localized message and a concrete next step.
 * The MCP server reduces the codes to the five public MCP codes via
 * [`ErrorCode::mcp_code`].
 */
export type ErrorCode = "UNAVAILABLE" | "BUSY" | "STALE" | "UNSUPPORTED" | "INTERNAL" | "INVALID_INPUT" | "NOT_FOUND" | "NOT_AUTHORIZED" | "OFFLINE" | "PREREQUISITE_MISSING" | "PLAN_CHANGED" | "CONFLICT" | "BLOCKED" | "TRANSACTION_FAILED" | "DEPENDENCY_PROBLEM";
