// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Other update mechanisms found on the system.
 */
export type ExternalUpdater = { 
/**
 * Unit or program name, e.g. `arch-update.timer`.
 */
name: string, 
/**
 * `system` or `user` unit.
 */
scope: string, active: boolean, description: string, };
