// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GpuInfo = { vendor: string, model: string, driver: string | null, 
/**
 * PCI id `vvvv:dddd` (no serial numbers).
 */
pciId: string, };
