// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthItemKind } from "./HealthItemKind";
import type { Severity } from "./Severity";

export type HealthItem = { kind: HealthItemKind, severity: Severity, 
/**
 * Short technical detail (English). Contains no personal paths.
 */
detail: string, 
/**
 * Optional count for the localized text.
 */
count: number | null, };
