// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFileHint } from "./ConfigFileHint";
import type { ExternalUpdater } from "./ExternalUpdater";
import type { HealthItem } from "./HealthItem";
import type { LockStatus } from "./LockStatus";
import type { OfflineUpdateStatus } from "./OfflineUpdateStatus";
import type { SnapshotSupport } from "./SnapshotSupport";

/**
 * Aggregated health report (UI health center, dashboard card, MCP `health_get`).
 */
export type HealthReport = { items: Array<HealthItem>, pacnewCount: number, pacsaveCount: number, configFiles: Array<ConfigFileHint>, lock: LockStatus, rebootRecommended: boolean, rebootReasons: Array<string>, packageCacheBytes: number | null, snapshot: SnapshotSupport, offlineUpdate: OfflineUpdateStatus, externalUpdaters: Array<ExternalUpdater>, 
/**
 * Reasons that currently block an unattended update preparation.
 */
updateBlockers: Array<string>, collectedAt: number, };
