// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifiers of health items. The UI renders localized texts for them.
 */
export type HealthItemKind = "pacnewFiles" | "pacsaveFiles" | "rebootRecommended" | "packageManagerLocked" | "lastOperationFailed" | "interruptedTransaction" | "packageCacheLarge" | "prerequisiteMissing" | "packageBackendUnavailable" | "updateCheckFailed" | "updateCheckStale" | "offlineUpdatePrepared" | "offlineConfHoldsPackages" | "externalUpdaterActive" | "newsUnread" | "newsUnavailable" | "lowDiskSpace";
