// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source of a history entry.
 */
export type HistorySource = "app" | "timer" | "externalPacman";
