// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { HistorySource } from "./HistorySource";
import type { LogOutcome } from "./LogOutcome";
import type { OperationKind } from "./OperationKind";
import type { OperationOrigin } from "./OperationOrigin";
import type { OperationState } from "./OperationState";

/**
 * One entry of the activity list. Contains no raw logs and no file paths.
 */
export type HistoryEntry = { id: string, source: HistorySource, kind: OperationKind | null, origin: OperationOrigin | null, state: OperationState | null, logOutcome: LogOutcome | null, startedAt: number, endedAt: number | null, summary: string, errorCode: ErrorCode | null, installed: number, upgraded: number, removed: number, downgraded: number, 
/**
 * Updates found by a successful update check; `None` for all other entries.
 */
updatesFound: number | null, 
/**
 * Up to 20 affected package names.
 */
packages: Array<string>, outcomeUnknown: boolean, };
