// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HyprMonitor = { name: string, description: string, width: number, height: number, refreshRate: number, scale: number, focused: boolean, activeWorkspace: string | null, };
