// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HyprMonitor } from "./HyprMonitor";
import type { HyprUnavailableReason } from "./HyprUnavailableReason";

/**
 * Hyprland information. Only available inside an active Hyprland session.
 */
export type HyprlandInfo = { available: boolean, reason: HyprUnavailableReason | null, version: string | null, monitors: Array<HyprMonitor>, activeWorkspace: string | null, workspaceCount: number | null, 
/**
 * Window class / app-id of cachyos-center for Hyprland window rules.
 */
appClass: string, collectedAt: number, };
