// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter for the installed package list.
 */
export type InstalledFilter = "all" | "explicit" | "dependency" | "repo" | "localOrAur" | "updateAvailable";
