// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Install reason as recorded in the local pacman database.
 */
export type InstallReason = "explicit" | "dependency";
