// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledFilter } from "./InstalledFilter";

/**
 * Query for the installed package list.
 */
export type InstalledQuery = { query: string | null, filter: InstalledFilter, offset: number, limit: number, };
