// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KernelInfo = { release: string, 
/**
 * Package base of the running kernel (`/usr/lib/modules/$(uname -r)/pkgbase`).
 */
package: string | null, uptimeSeconds: number, 
/**
 * The module directory of the running kernel is missing (kernel was updated).
 */
modulesMissing: boolean, };
