// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of the pacman database lock (`db.lck`).
 */
export type LockStatus = { "state": "free" } | { "state": "locked", since: number | null, 
/**
 * A running pacman-like process was found (`None` when not determinable).
 */
holderRunning: boolean | null, };
