// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of an external pacman transaction reconstructed from the pacman log.
 */
export type LogOutcome = "completed" | "failed" | "interrupted" | "unknown";
