// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information for the MCP settings section.
 */
export type McpSetup = { enabled: boolean, 
/**
 * Absolute path of `cachyos-center-mcp` (`None` when not found).
 */
binaryPath: string | null, 
/**
 * Example host configuration (JSON, `mcpServers` format) with the absolute path.
 */
hostConfig: string, 
/**
 * Names of the read-only tools offered by the server.
 */
tools: Array<string>, };
