// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewsFeedError } from "./NewsFeedError";
import type { NewsItem } from "./NewsItem";

export type NewsStatus = { 
/**
 * News fetching is disabled in the settings.
 */
disabled: boolean, items: Array<NewsItem>, fetchedAt: number | null, 
/**
 * Feeds that could not be fetched ("News-Check nicht möglich").
 */
errors: Array<NewsFeedError>, acknowledgedUntil: number | null, unreadCount: number, };
