// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewsSource } from "./NewsSource";

export type NewsFeedError = { source: NewsSource, message: string, };
