// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewsSource } from "./NewsSource";

export type NewsItem = { source: NewsSource, title: string, 
/**
 * `https://` link to the official announcement.
 */
link: string, publishedAt: number, unread: boolean, };
