// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the external `pacman-offline` integration.
 */
export type OfflineUpdateStatus = { 
/**
 * `/usr/bin/pacman-offline` exists.
 */
installed: boolean, 
/**
 * `/system-update` points to the pacman cache: an update is prepared for the next reboot.
 */
prepared: boolean, 
/**
 * `pacman-offline-prepare.timer` is enabled or active (externally managed).
 */
prepareTimerActive: boolean, 
/**
 * `pacman-offline-reboot.timer` is enabled or active.
 */
rebootTimerActive: boolean, 
/**
 * `Include = /etc/pacman.d/offline.conf` is active in `/etc/pacman.conf`.
 */
offlineConfIncluded: boolean, 
/**
 * Packages held back for online updates by `offline.conf`.
 */
offlineConfIgnored: Array<string>, 
/**
 * The configuration could be inspected completely.
 */
configurationVerifiable: boolean, };
