// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Part of an operation log (`ReadOperationLog`).
 */
export type OperationLogChunk = { lines: Array<string>, 
/**
 * Byte offset for the next request.
 */
nextOffset: number, 
/**
 * The operation has ended and the log is complete.
 */
complete: boolean, };
