// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of an operation (see module documentation for the transitions).
 */
export type OperationState = "idle" | "checking" | "ready" | "awaitingAuthorization" | "preparing" | "downloading" | "installing" | "succeeded" | "failed" | "needsAttention" | "cancelledBeforeCommit";
