// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step of the helper within a state. Stable identifiers; the UI renders
 * localized texts.
 */
export type OperationStep = "waitingForLock" | "synchronizingDatabases" | "downloadingPackages" | "applyingChanges";
