// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { OperationKind } from "./OperationKind";
import type { OperationOrigin } from "./OperationOrigin";
import type { OperationState } from "./OperationState";
import type { Progress } from "./Progress";
import type { SnapshotResult } from "./SnapshotResult";
import type { TransactionPlan } from "./TransactionPlan";

/**
 * A package operation tracked by the helper, the timer or the UI.
 */
export type Operation = { id: string, kind: OperationKind, origin: OperationOrigin, requestedAt: number, state: OperationState, 
/**
 * Packages named by the user (install/remove) – empty for upgrades.
 */
packageTargets: Array<string>, startedAt: number | null, endedAt: number | null, 
/**
 * Exit code of the pacman step that ended the operation.
 */
exitCode: number | null, 
/**
 * Short English summary; the UI renders a localized text from state and error code.
 */
summary: string, error: AppError | null, 
/**
 * `true` as soon as the pacman commit phase may have started.
 */
commitStarted: boolean, 
/**
 * Plan confirmed by the user.
 */
confirmedDigest: string | null, 
/**
 * Actual plan computed before the commit (set on [`ErrorCode::PlanChanged`]).
 */
actualPlan: TransactionPlan | null, progress: Progress, snapshot: SnapshotResult | null, 
/**
 * Number of `.pacnew`/`.pacsave` files reported by pacman during the transaction.
 */
newPacnewFiles: number, 
/**
 * Result could not be determined with certainty (e.g. after a crash).
 */
outcomeUnknown: boolean, };
