// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OsInfo = { id: string, name: string, prettyName: string, buildId: string | null, isCachyos: boolean, 
/**
 * `ID=arch` or `ID_LIKE` contains `arch`.
 */
isArchBased: boolean, };
