// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallReason } from "./InstallReason";
import type { PackageId } from "./PackageId";
import type { PackageOrigin } from "./PackageOrigin";

/**
 * Full package record shown in the details view.
 */
export type PackageRecord = { id: PackageId, description: string, origin: PackageOrigin, installedVersion: string | null, availableVersion: string | null, installReason: InstallReason | null, url: string | null, licenses: Array<string>, groups: Array<string>, dependencies: Array<string>, optionalDependencies: Array<string>, requiredBy: Array<string>, optionalFor: Array<string>, provides: Array<string>, conflicts: Array<string>, replaces: Array<string>, installedSize: number | null, downloadSize: number | null, packager: string | null, buildDate: number | null, installDate: number | null, 
/**
 * Package is considered system critical and gets an additional warning before removal.
 */
critical: boolean, ignored: boolean, };
