// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageSummary } from "./PackageSummary";

/**
 * One page of results.
 */
export type PackagePage = { items: Array<PackageSummary>, total: number, offset: number, 
/**
 * Offset of the next page, `None` on the last page.
 */
nextOffset: number | null, };
