// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an installed or available package comes from.
 *
 * `LocalOrAur` is determined via "foreign packages" (installed but not present
 * in any configured sync repository). This is only an approximation: the UI
 * labels it "Lokal/AUR (Quelle nicht sicher bestimmbar)".
 */
export type PackageOrigin = "repo" | "localOrAur" | "flatpak";
