// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallReason } from "./InstallReason";
import type { PackageOrigin } from "./PackageOrigin";

/**
 * Compact list entry for installed packages and repository search results.
 */
export type PackageSummary = { name: string, description: string, 
/**
 * Sync repository providing the package (`None` for foreign packages).
 */
repository: string | null, origin: PackageOrigin, architecture: string, installedVersion: string | null, 
/**
 * Version in the sync repository (newest over all repositories in pacman order).
 */
availableVersion: string | null, installReason: InstallReason | null, installedSize: number | null, 
/**
 * Installed and a newer version is available in a sync repository.
 */
updateAvailable: boolean, 
/**
 * Listed in `IgnorePkg`/`IgnoreGroup` (held back by pacman configuration).
 */
ignored: boolean, };
