// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to a package for the details view.
 */
export type PackageRef = { name: string, 
/**
 * Sync repository to look in; `None` looks at the installed package first.
 */
repository: string | null, };
