// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `repository + packageName + architecture`.
 *
 * For foreign packages the repository is `"local"`.
 */
export type PackageId = { repository: string, name: string, architecture: string, };
