// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendStatus } from "./BackendStatus";
import type { LockStatus } from "./LockStatus";

export type PacmanStatus = { pacmanVersion: string | null, backend: BackendStatus, lock: LockStatus, lastFullUpgrade: number | null, installedCount: number, foreignCount: number, repositories: Array<string>, };
