// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanEntry } from "./PlanEntry";

/**
 * Difference between two plans.
 */
export type PlanDiff = { added: Array<PlanEntry>, removed: Array<PlanEntry>, changed: Array<PlanEntry>, };
