// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanAction } from "./PlanAction";
import type { UpdateFlag } from "./UpdateFlag";

/**
 * One package in a plan.
 */
export type PlanEntry = { action: PlanAction, name: string, 
/**
 * Sync repository for installs/upgrades, `None` for removals.
 */
repository: string | null, oldVersion: string | null, newVersion: string | null, downloadSize: number | null, 
/**
 * Explicitly requested by the user (as opposed to pulled in by dependencies or the upgrade).
 */
requested: boolean, flags: Array<UpdateFlag>, };
