// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Action pacman takes for one package.
 */
export type PlanAction = "install" | "upgrade" | "downgrade" | "reinstall" | "remove";
