// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Non-fatal notes attached to a plan.
 */
export type PlanWarning = { "kind": "includesSystemUpgrade", upgradeCount: number, } | { "kind": "criticalPackages", packages: Array<string>, } | { "kind": "heldBackPackages", packages: Array<string>, } | { "kind": "rebootRecommended", packages: Array<string>, } | { "kind": "replacements", packages: Array<string>, };
