// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationStep } from "./OperationStep";

/**
 * Coarse progress information. No overall percentage is estimated: only
 * values backed by pacman output are reported.
 */
export type Progress = { 
/**
 * Package pacman is currently working on (from the pacman log).
 */
currentPackage: string | null, 
/**
 * Number of packages pacman has finished in the commit phase.
 */
packagesDone: number, 
/**
 * Number of packages in the verified plan.
 */
packagesTotal: number | null, 
/**
 * What the helper is doing within the current state.
 */
step: OperationStep | null, };
