// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a reboot is recommended. The UI renders localized texts.
 */
export type RebootReason = { "kind": "kernelReplaced" } | { "kind": "updatedSinceBoot", packages: Array<string>, };
