// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configured sync repository as reported by `pacman-conf`.
 */
export type RepositoryInfo = { name: string, packageCount: number, };
