// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionKind } from "./SessionKind";

export type SessionInfo = { kind: SessionKind, 
/**
 * `XDG_CURRENT_DESKTOP` (e.g. `Hyprland`, `KDE`).
 */
desktop: string | null, 
/**
 * `XDG_SESSION_TYPE` (`wayland`, `x11`, `tty`).
 */
sessionType: string | null, };
