// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Density } from "./Density";
import type { LanguagePreference } from "./LanguagePreference";
import type { ThemePreference } from "./ThemePreference";

export type Settings = { theme: ThemePreference, language: LanguagePreference, density: Density, 
/**
 * Desktop notifications for updates, results, errors and `NeedsAttention`.
 */
notifications: boolean, 
/**
 * Background update check while the app is running (hours, 0 = off).
 */
checkIntervalHours: number, 
/**
 * Retention of the local history and operation logs.
 */
logRetentionDays: number, 
/**
 * Fetch Arch Linux and CachyOS news (network access to archlinux.org/cachyos.org).
 */
newsEnabled: boolean, 
/**
 * The local read-only MCP server answers requests (off by default).
 */
mcpEnabled: boolean, };
