// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of an explicitly requested snapshot.
 */
export type SnapshotResult = { 
/**
 * `true` only when snapper confirmed the snapshot number.
 */
created: boolean, snapperConfig: string, number: number | null, error: string | null, };
