// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapper/Btrfs snapshot support. Only reports what could be verified.
 */
export type SnapshotSupport = { 
/**
 * Root filesystem is Btrfs.
 */
btrfsRoot: boolean, 
/**
 * `snapper` is installed.
 */
snapperInstalled: boolean, 
/**
 * A snapper configuration for `/` exists (name of the config, usually `root`).
 */
rootConfig: string | null, 
/**
 * `snap-pac` creates pre/post snapshots for every pacman transaction.
 */
snapPacActive: boolean, 
/**
 * `true` when cachyos-center can request a snapshot before an upgrade.
 */
canRequestSnapshot: boolean, };
