// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuInfo } from "./CpuInfo";
import type { DiskInfo } from "./DiskInfo";
import type { GpuInfo } from "./GpuInfo";
import type { KernelInfo } from "./KernelInfo";
import type { MemoryInfo } from "./MemoryInfo";
import type { OsInfo } from "./OsInfo";
import type { PacmanStatus } from "./PacmanStatus";
import type { SessionInfo } from "./SessionInfo";

/**
 * Complete system information for the "System" page.
 */
export type SystemInfo = { os: OsInfo, kernel: KernelInfo, cpu: CpuInfo, gpus: Array<GpuInfo>, memory: MemoryInfo, disks: Array<DiskInfo>, session: SessionInfo, pacman: PacmanStatus, collectedAt: number, };
