// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionKind } from "./SessionKind";

/**
 * Reduced summary for the dashboard and the MCP tool `system_get_summary`.
 */
export type SystemSummary = { os: string, isCachyos: boolean, kernel: string, uptimeSeconds: number, cpu: string, gpus: Array<string>, memoryTotalBytes: number, memoryAvailableBytes: number, rootTotalBytes: number, rootAvailableBytes: number, rootFilesystem: string, session: SessionKind, desktop: string | null, pacmanVersion: string | null, packageBackendReady: boolean, };
