// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanEntry } from "./PlanEntry";
import type { PlanKind } from "./PlanKind";
import type { PlanSource } from "./PlanSource";
import type { PlanWarning } from "./PlanWarning";

/**
 * Complete, reviewable package transaction.
 */
export type TransactionPlan = { kind: PlanKind, 
/**
 * Targets named by the user (empty for a system upgrade).
 */
targets: Array<string>, entries: Array<PlanEntry>, downloadSize: number, 
/**
 * Change of installed size in bytes (negative when space is freed).
 */
installSizeDelta: number, source: PlanSource, computedAt: number, warnings: Array<PlanWarning>, 
/**
 * Remove unneeded dependencies as well (`-Rs`), only for [`PlanKind::Remove`].
 */
recursive: boolean, 
/**
 * Lower-case hex SHA-256 over the canonical plan (see [`TransactionPlan::digest_of`]).
 */
digest: string, };
