// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageId } from "./PackageId";
import type { UpdateFlag } from "./UpdateFlag";

/**
 * One available update.
 */
export type UpdateCandidate = { packageId: PackageId, oldVersion: string, newVersion: string, 
/**
 * Download size if the package is not cached yet. `None` when unknown.
 */
downloadSize: number | null, flags: Array<UpdateFlag>, };
