// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification of an update. Used for badges and restart hints.
 */
export type UpdateFlag = "kernel" | "driver" | "firmware" | "microcode" | "coreSystem" | "packageManager" | "desktopSession" | "heldBack" | "rebootRecommended";
