// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Weekday } from "./Weekday";

/**
 * Weekdays and time for the scheduled preparation/notification.
 */
export type UpdateWindow = { weekdays: Array<Weekday>, 
/**
 * `HH:MM`, 24 hour clock, local time.
 */
time: string, };
