// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { CheckStatus } from "./CheckStatus";
import type { TransactionPlan } from "./TransactionPlan";
import type { UpdateCandidate } from "./UpdateCandidate";

/**
 * Result of an update check including uncertainty information.
 */
export type UpdateCheckResult = { status: CheckStatus, 
/**
 * Time of the last *successful* synchronization of the isolated database.
 */
checkedAt: number | null, 
/**
 * Time of the last attempt (successful or not).
 */
attemptedAt: number | null, 
/**
 * Updates that a full `pacman -Syu` would install (derived from `plan`).
 */
updates: Array<UpdateCandidate>, 
/**
 * Complete upgrade plan computed from the isolated database. Its digest is
 * the preview the user confirms; the helper recomputes it before commit.
 */
plan: TransactionPlan | null, 
/**
 * Newer versions that pacman holds back (`IgnorePkg`, e.g. via `offline.conf`).
 */
heldBack: Array<UpdateCandidate>, totalDownloadSize: number | null, rebootRecommended: boolean, 
/**
 * Error of the most recent failed attempt.
 */
error: AppError | null, 
/**
 * Missing programs for [`CheckStatus::PrerequisiteMissing`] (package names).
 */
missingPrerequisites: Array<string>, };
