// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifiers of reasons that block an unattended update preparation.
 * The UI renders localized texts for them.
 */
export type UpdateBlocker = "packageManagerBusy" | "lastTransactionIncomplete" | "lastOperationNeedsAttention" | "packageBackendUnavailable" | "prerequisitesMissing" | "externalPrepareTimer" | "newsUnread" | "newsUnavailable" | "newsDisabled" | "lowDiskSpace";
